[providers]
node = "18"

[variables]
NIXPACKS_NODE_VERSION = "18"
NODE_VERSION = "18"
CI = "false"
DISABLE_ESLINT_PLUGIN = "false"
GENERATE_SOURCEMAP = "false"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[start]
cmd = "npm start" 