[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["CI=false DISABLE_ESLINT_PLUGIN=true npm run build"]

[start]
cmd = "npx serve -s build -l $PORT" 